name: Copy Branch to test_repo_2

on:
  workflow_dispatch:

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Get short commit hash
      id: get_commit_hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Configure SSH for deployment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

    - name: Check git status
      run: git status

    - name: Push branch to test_repo_2
      env:
        NEW_BRANCH_NAME: "${{ github.ref_name }}-${{ env.hash }}"
      run: |
        git checkout -b $NEW_BRANCH_NAME
        git config --global user.email "deploy@crypton.studio"
        git config --global user.name "Deploy Crypton"
        git remote add target git@github.com:asychin/test_repo_2.git
        git add .
        git commit --allow-empty -m "Crypto Gateway Release: ${{ github.ref_name }}"
        git push -u target $NEW_BRANCH_NAME
