name: Copy Branch to test_repo_2

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to copy from (dev or stage)'
        required: true
        default: 'main'

jobs:
  copy-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.target_branch }}

    - name: Get short commit hash
      id: get_commit_hash
      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Configure SSH for deployment
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -t rsa github.com
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no"
        cat ~/.ssh/deploy_key

    - name: Debugging SSH connection
      run: |
        # Check if the SSH key is working correctly
        ssh -T git@github.com

    - name: Push branch to test_repo_2
      env:
        NEW_BRANCH_NAME: "${{ github.event.inputs.target_branch }}#${{ env.hash }}"
      run: |
        # Create new branch name
        git branch $NEW_BRANCH_NAME

        # Push branch to target repository
        git remote add target git@github.com:asychin/test_repo_2.git
        git push target $NEW_BRANCH_NAME
